#server port
server:
  port: 31100


#smtp configuration and database configuration
spring:
  main:
    allow-circular-references: true
  datasource:
    #    url: jdbc:postgresql://localhost:5432/Foundation
    url: jdbc:postgresql://database-1.cp0sfdcoljwx.us-east-1.rds.amazonaws.com:5432/AwsDataBase
#    url: jdbc:postgresql://careerfund.postgres.database.azure.com:5432/careerfundAzure
    username: postgres
#    username: careerfund@careerfund
#    password: Azure@123
  #    password: root
    password: Saikumar
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


  #  gmail smtp configurations
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: devisaikotari@gmail.com
    password: toqqybbrwtpzfovq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#eureka configuration
eureka:
  instance:
    hostname: postgresdb.cu0ghcs3xhjo.us-east-1.rds.amazonaws.com
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://postgresdb.cu0ghcs3xhjo.us-east-1.rds.amazonaws.com:5432/eureka/



#Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html


#spring security
logging:
  level:
    org:
      springframework:
        security: DEBUG


