#server port
server:
  port: 9090

jwt:
  secret: f82e3ba1a4d359ef0a37815c379d216999473e0b7f425f86c65e78c2a1380dca

#smtp configuration and database configuration
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/careerfundDB
    url: jdbc:postgresql://database-1.crc20wkc223a.eu-north-1.rds.amazonaws.com:5432/DemoDB
    username: postgres
    password: mahesh$106
#    password: SaiKumar
#    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


  #  gmail smtp configurations
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: devisaikotari@gmail.com
    password: toqqybbrwtpzfovq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#eureka configuration
eureka:
  instance:
    hostname: postgresdb.cu0ghcs3xhjo.us-east-1.rds.amazonaws.com
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://postgresdb.cu0ghcs3xhjo.us-east-1.rds.amazonaws.com:5432/eureka/



#Swagger
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html


#spring security
logging:
  level:
    org:
      springframework:
        security: DEBUG



#s3 configuration
aws:
  region: eu-north-1
  s3:
    BucketName: careerfund-images
    AdminFolder: Admin_images
    ArticleFolder: Articles_images
    BlogFolder: Blog_images
    ClientFolder: Client_images
    DonorFolder: Donor_images
    EventsFolder: Events_images
    StudentFolder: Student_images
    SuccessStoriesFolder: SuccessStories_images
    TechnologiesFolder: Technologies_images
    TrainerFolder: Trainer_images
    AdvertisementFolder: Advertisement_images



